apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wg5dy0pce-python 
  janus-idp.io/tekton: wg5dy0pce-python
  backstage.io/kubernetes-id: wg5dy0pce-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wg5dy0pce-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml