apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wg5dy0pce-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wg5dy0pce-python 
  name: wg5dy0pce-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wg5dy0pce-python 
